version: 2.1

jobs:
  terraform-validate:
    resource_class: small
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - run: |
          echo "foo"

workflows:
  main:
    jobs:
      - terraform-validate
