version: 2.1

executors:
  basic:
    docker:
      - image: cimg/base:stable
    resource_class: small

commands:
  my-checkout:
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}
          paths:
            - ".git"

jobs:
  checkout-org-context:
    executor: basic
    steps:
      - checkout
      - run: |
          # check out the org context!
          # should print 'spoon', but masked
          printenv FORK
  custom-checkout:
    executor: basic
    steps:
      - my-checkout
  on-forked-repo-only:
    executor: basic
    steps:
      - checkout
      - run: |
          env | grep CIRCLE_
workflows:
  main:
    jobs:
      - custom-checkout
      - on-forked-repo-only
