version: 2.1

executors:
  basic:
    docker:
      - image: cimg/base:stable
    resource_class: small

commands:
  my-checkout:
    parameters:
      use-cache:
        type: boolean
        default: false
    steps:
      - run: |
          git version
      - when:
          condition: << parameters.use-cache >>
          steps:
            - restore_cache:
                keys:
                  - source-v1-{{ .Branch }}
                  - source-v1-
      - checkout
      - when:
          condition: << parameters.use-cache >>
          steps:
            - save_cache:
                key: source-v1-{{ .Branch }}
                paths:
                  - ".git"
      - run: |
          ls -laH .

jobs:
  checkout-org-context:
    executor: basic
    steps:
      - checkout
      - run: |
          # check out the org context!
          # should print 'spoon'
          printenv FORK
  checkout:
    parameters:
      use-cache:
        type: boolean
        default: false
    executor: basic
    steps:
      - my-checkout:
          use-cache: << parameters.use-cache >>

workflows:
  main:
    jobs:
      - checkout:
          matrix:
            parameters:
              use-cache:
                - true
                - false
